version: '3.8'

services:
  db:
    image: postgres:13
    container_name: feedback_db_container
    environment:
      POSTGRES_DB: feedback_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: